[package]
name = "opendeck"
version = "0.1.0"
edition = "2021"
categories = ["no-std", "embedded"]

[dependencies]
midi2 = { version = "0.6.3", default-features = false, features = [
  "channel-voice1",
  "channel-voice2",
  "sysex7",
  "sysex8",
  "flex-data",
  "system-common",
  "ump-stream",
  "utility",
] }
defmt = { version = "0.3.10", optional = true }
heapless = { version = "0.8.0", features = ["defmt-03"] }
int-enum = "1.1.2"

[features]
default = ["defmt"]
defmt = ["dep:defmt"]
